Add fp solution
Chirkovl/study pull request #2
Opened 2021-11-19 12:44 UTC by Chirkovl

2021-11-19 19:42 UTC, NickelGit requested changes

2021-11-19 19:42 UTC, NickelGit commented on test/exercise/fp/solution.rb
> +        films_with_rating = array.select { |film| film['rating_kinopoisk'].to_f.positive? && !film['country'].nil? && film['country'].split(',').length > 1 }
Давай вынесем все условия в отдельный метод с говорящим названием и в селите будем вызывать его.
Подробнее про сокращение длинных условий можно посмотреть в "ментальном программировании"  (https://youtu.be/eEEHWQNuCLQ?t=691)

2021-11-25 16:51 UTC, Chirkovl commented on test/exercise/fp/solution.rb
> +        films_with_rating = array.select { |film| film['rating_kinopoisk'].to_f.positive? && !film['country'].nil? && film['country'].split(',').length > 1 }
> 
В данном случае нужно передать в этот "условный'' метод блок? Просто есть не полное понимание с точки зрения ментального программирования.

2021-12-07 11:02 UTC, NickelGit commented on test/exercise/fp/solution.rb
> +        films_with_rating = array.select { |film| film['rating_kinopoisk'].to_f.positive? && !film['country'].nil? && film['country'].split(',').length > 1 }
В аргументы метода необходимо просто передать `film` в данном случае, внутри метода проверить всем ли условиям этот фильм соответствует и вернуть `true` или `false` , а внутри `select` уже вызывать этот метод.
Т.е. что то вроде 
```
def rated_and_has_several_countries?(film)
   film['rating_kinopoisk'].to_f.positive? && !film['country'].nil? && film['country'].split(',').length > 1
end
```

`...select{ |film| rated_and_has_several_countries?(film) }`

2021-12-09 15:31 UTC, Chirkovl commented on test/exercise/fp/solution.rb
> +        films_with_rating = array.select { |film| film['rating_kinopoisk'].to_f.positive? && !film['country'].nil? && film['country'].split(',').length > 1 }
> В аргументы метода необходимо просто передать `film` в данном случае, внутри метода проверить всем ли условиям этот фильм соответствует и вернуть `true` или `false` , а внутри `select` уже вызывать этот метод. Т.е. что то вроде
> 
> ```
> def rated_and_has_several_countries?(film)
>    film['rating_kinopoisk'].to_f.positive? && !film['country'].nil? && film['country'].split(',').length > 1
> end
> ```
> 
> `...select{ |film| rated_and_has_several_countries?(film) }`

Я понял. Если вы не против, использую этот метод))

2021-12-10 08:15 UTC, NickelGit commented on test/exercise/fp/solution.rb
> +        end
вынеси пожалуйста этот метод наружу, т.е. что бы он небыл внутри другого метода.
```
def rated_and_has_several_countries?(film)
  ...
end

def rating(array)
  ...
end
```

2021-12-13 07:05 UTC, NickelGit approved these changes

2021-12-13 14:59 UTC, merged